openapi: 3.0.1
info:
  title: Login API
  description: login
  version: '1'
servers:
  - url: http://localhost:8000
paths:
  /refresh:
    post:
      description: Refresh tokens
      parameters:
        - name: User
          in: header
          schema:
            type: string
          example: '1'
      security: 
      - oauth2: []
      responses:
        '202':
          description: Susccse refresh
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
              examples:
                '0':
                  value: >
                    {"id":"1","accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYwMTg0NTcsImlkIjoiMSJ9.o2WUdgr4pzAFQeDGpRel7WNGd5woG1TcUUol82HrNkU","refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxMDQ3OTcsImlkIjoiMSJ9.wpQ1-Abp5gZ9D0lxZaI4gB8v0Nqou9u-rKVi1SvFy5A"}
        '400':
          description: Incorrect login pass
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              examples: { }
        '401':
          description: invalid auth
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              examples: { }
      servers:
        - url: http://localhost:8000
    servers:
      - url: http://localhost:8000
  /user:
    post:
      description: Check Is user in system
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                login:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "login":"swag@swag.swag",
                      "password":"swag"
                  }
      security: 
      - oauth2: []
      responses:
        '200':
          description: User in system
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              examples: {}
        '401':
          description: invalid auth
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost:8000
    servers:
      - url: http://localhost:8000
  /signin:
    post:
      description: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                login:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "login":"swag@swag.swag",
                      "password":"swag"
                  }
              '1':
                value: |-
                  {
                      "login":"swag@swag.swaaa",
                      "password":"swag"
                  }
      responses:
        '202':
          description: Success login
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
              examples:
                '0':
                  value: >
                    {"id":"1","accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYwMTgxMDksImlkIjoiMSJ9.aqsZdhFqMjws2WQLMtg0H0OFOnjOOWsCkSnY6QrNbPc","refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxMDQ0NDksImlkIjoiMSJ9.MYx5kzHW8EH5r5iXmiyIkSl_aNUGbyZfi-yF0Q_Pci0"}
        '400':
          description: Incorrect login pass
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost:8000
    servers:
      - url: http://localhost:8000
  /signup:
    post:
      description: User registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                login:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "login":"swag@swag.swag",
                      "password":"swag"
                  }
      responses:
        '200':
          description: Success registration
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              examples: {}
        '400':
          description: Incorrect login pass
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost:8000
    servers:
      - url: http://localhost:8000
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost:8000/user
          scopes:
            scope_name: ///